FROM node:22-bookworm-slim AS deps
WORKDIR /app
COPY package.json package-lock.json ./
RUN --mount=type=cache,target=/root/.npm npm ci --no-audit --no-fund

FROM node:22-bookworm-slim AS builder
WORKDIR /app
ENV NEXT_TELEMETRY_DISABLED=1
COPY --from=deps /app/node_modules ./node_modules
COPY . .

ARG NEXT_PUBLIC_META_PIXEL_ID
ENV NEXT_PUBLIC_META_PIXEL_ID=$NEXT_PUBLIC_META_PIXEL_ID
ARG NEXT_PUBLIC_VIBECODE_CHECKOUT_URL
ENV NEXT_PUBLIC_VIBECODE_CHECKOUT_URL=$NEXT_PUBLIC_VIBECODE_CHECKOUT_URL
ARG NEXT_PUBLIC_FORMACAO_COMPLETA_CHECKOUT_URL
ENV NEXT_PUBLIC_FORMACAO_COMPLETA_CHECKOUT_URL=$NEXT_PUBLIC_FORMACAO_COMPLETA_CHECKOUT_URL
ARG NEXT_PUBLIC_RABBITMQ_CHECKOUT_URL
ENV NEXT_PUBLIC_RABBITMQ_CHECKOUT_URL=$NEXT_PUBLIC_RABBITMQ_CHECKOUT_URL
ARG NEXT_PUBLIC_RABBITMQ_YOUTUBE_VIDEO_ID
ENV NEXT_PUBLIC_RABBITMQ_YOUTUBE_VIDEO_ID=$NEXT_PUBLIC_RABBITMQ_YOUTUBE_VIDEO_ID
ARG NEXT_PUBLIC_SAAS_PRICE
ENV NEXT_PUBLIC_SAAS_PRICE=$NEXT_PUBLIC_SAAS_PRICE
ARG NEXT_PUBLIC_SAAS_CHECKOUT_URL
ENV NEXT_PUBLIC_SAAS_CHECKOUT_URL=$NEXT_PUBLIC_SAAS_CHECKOUT_URL
ARG NEXT_PUBLIC_ARCHITECTURE_CHECKOUT_URL
ENV NEXT_PUBLIC_ARCHITECTURE_CHECKOUT_URL=$NEXT_PUBLIC_ARCHITECTURE_CHECKOUT_URL

RUN npm run build

FROM node:22-bookworm-slim AS runner
WORKDIR /app
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=3000
ENV HOSTNAME=0.0.0.0
RUN addgroup --system --gid 1001 nodejs && adduser --system --uid 1001 nextjs
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
COPY --from=builder --chown=nextjs:nodejs /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/scripts ./scripts
COPY --from=builder --chown=nextjs:nodejs /app/db ./db
USER nextjs
EXPOSE 3000
CMD ["sh", "-c", "node scripts/migrate.mjs && node server.js"]
