import Link from "next/link";
import { ArrowRight, Bot, BrainCircuit, Check, CheckCircle2, Code2, Infinity, Layers3, MessageSquareMore, RefreshCw, Rocket, ShieldCheck, Sparkles, Workflow, Zap } from "lucide-react";
import { MetaPixelScript } from "@/components/MetaPixelScript";
import { SalesPageTracker, SalesViewContentTracker } from "@/components/SalesPageTracker";
import { MobileStickyCTA, SectionViewTracker, TrackedAccordion, TrackedCheckoutButton } from "@/components/course-completo/interactive";

type Props = { checkoutUrl: string; metaPixelId?: string };
const PAGE_KEY = "formacao-completa";
const PAGE_PATH = "/formacao-completa";
const PAGE_TITLE = "Formação Completa Plugando IA | 5 cursos com acesso vitalício";
const PRICE = 149.9;
const REGULAR_PRICE = 399.5;
const SAVINGS = REGULAR_PRICE - PRICE;

const courses = [
  { number: "01", title: "Vibe Coding para Leigos", href: "/vibecode", icon: Sparkles, color: "text-fuchsia-200 bg-fuchsia-300/10 border-fuchsia-300/25", promise: "Transforme uma ideia em aplicação com ChatGPT e Codex, mesmo sem experiência com programação.", topics: ["Planejamento e SPEC", "ChatGPT + Codex", "Projeto real completo", "Testes, Git e publicação"] },
  { number: "02", title: "Arquitetura de Software", href: "/curso-arquitetura-software", icon: Layers3, color: "text-emerald-300 bg-emerald-400/10 border-emerald-400/25", promise: "Aprenda a tomar decisões técnicas e organizar sistemas que podem crescer sem virar um emaranhado.", topics: ["SOLID e princípios de design", "Modelos arquiteturais", "Integração e resiliência", "C#, API .NET e AWS incluídos"] },
  { number: "03", title: "RabbitMQ com .NET", href: "/curso-rabbitmq", icon: MessageSquareMore, color: "text-orange-300 bg-orange-400/10 border-orange-400/25", promise: "Domine mensageria construindo um fluxo real de e-commerce, com falhas controladas e observabilidade.", topics: ["Producer, Consumer e Exchanges", "Retry, DLQ e idempotência", "Docker, Prometheus e Grafana", "Projeto prático de e-commerce"] },
  { number: "04", title: "Criando SaaS com Antigravity", href: "/curso-saas", icon: Rocket, color: "text-violet-300 bg-violet-400/10 border-violet-400/25", promise: "Transforme uma ideia em produto: do prompt e banco de dados ao trial, pagamento, Docker e deploy.", topics: ["Antigravity e Next.js", "Login, trial e assinatura", "Banco de dados e pagamentos", "Publicação de um produto real"] },
  { number: "05", title: "Fundamentos de IA Generativa", href: "/fundamentos-ia", icon: BrainCircuit, color: "text-amber-200 bg-amber-300/10 border-amber-300/25", promise: "Entenda o que existe por trás da IA e avance até uma aplicação que conversa, consulta dados e executa ações.", topics: ["LLMs e Prompt Engineering", "APIs, contexto e Tools", "Prisma e SQLite", "Aplicação completa com IA"] },
] as const;

function currency(value: number) { return value.toLocaleString("pt-BR", { style: "currency", currency: "BRL" }); }
function Heading({ eyebrow, title, description }: { eyebrow: string; title: string; description: string }) {
  return <div className="mx-auto max-w-3xl text-center"><p className="text-xs font-black uppercase tracking-[0.24em] text-cyan-300">{eyebrow}</p><h2 className="mt-4 text-balance text-3xl font-black tracking-[-0.04em] text-white sm:text-4xl md:text-5xl">{title}</h2><p className="mt-5 text-lg leading-8 text-slate-400">{description}</p></div>;
}

export function FormacaoCompletaLanding({ checkoutUrl, metaPixelId }: Props) {
  const checkoutReady = /^https?:\/\//.test(checkoutUrl);
  const eventData = { content_name: "Formação Completa Plugando IA", content_category: "Combo de cursos", content_type: "product", value: PRICE, currency: "BRL" };
  function Cta({ label, className = "" }: { label: string; className?: string }) {
    if (!checkoutReady) return <a href="#oferta" className={`inline-flex items-center justify-center rounded-xl bg-cyan-300 px-6 py-4 text-sm font-black text-slate-950 transition hover:bg-cyan-200 ${className}`}>{label}<ArrowRight className="ml-2 h-4 w-4" /></a>;
    return <TrackedCheckoutButton href={checkoutUrl} label={label} pageKey={PAGE_KEY} pagePath={PAGE_PATH} pageTitle={PAGE_TITLE} value={PRICE} currency="BRL" customEvent="formacao_completa_checkout_click" eventData={eventData} hideGlow className={`!rounded-xl !bg-none !bg-cyan-300 !px-6 !py-4 !font-black !text-slate-950 hover:!bg-cyan-200 ${className}`} />;
  }

  return <main className="min-h-screen overflow-hidden bg-[#060913] text-white">
    <MetaPixelScript pixelId={metaPixelId} />
    <SalesPageTracker pageKey={PAGE_KEY} pagePath={PAGE_PATH} pageTitle={PAGE_TITLE} metadata={{ offerPrice: PRICE, regularPrice: REGULAR_PRICE, currency: "BRL", offerName: "Formação Completa Plugando IA" }} />
    <SalesViewContentTracker pageKey={PAGE_KEY} pagePath={PAGE_PATH} pageTitle={PAGE_TITLE} currency="BRL" value={PRICE} metadata={{ contentName: "Formação Completa Plugando IA", contentType: "course_bundle" }} />
    <SectionViewTracker selectorId="cursos" pageKey={PAGE_KEY} pagePath={PAGE_PATH} pageTitle={PAGE_TITLE} eventName="courses_view" /><SectionViewTracker selectorId="oferta" pageKey={PAGE_KEY} pagePath={PAGE_PATH} pageTitle={PAGE_TITLE} eventName="offer_view" />

    <div className="border-b border-cyan-300/15 bg-cyan-300/[0.07] px-4 py-2.5 text-center text-xs font-bold text-cyan-100 sm:text-sm">5 cursos completos • acesso vitalício • futuras atualizações incluídas</div>
    <header className="border-b border-white/[0.08]"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4 md:px-8"><Link href="/cursos" className="text-lg font-black tracking-[-0.03em]">Plugando <span className="text-cyan-300">IA</span></Link><nav className="flex gap-5 text-sm font-semibold text-slate-400"><a href="#cursos" className="hidden hover:text-white sm:block">Os 5 cursos</a><a href="#oferta" className="hover:text-cyan-300">Ver oferta</a></nav></div></header>

    <section className="relative border-b border-white/[0.08]"><div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_75%_15%,rgba(34,211,238,.15),transparent_32%),radial-gradient(circle_at_15%_70%,rgba(139,92,246,.12),transparent_35%)]" /><div className="relative mx-auto grid max-w-7xl gap-12 px-5 py-14 md:px-8 md:py-20 lg:grid-cols-[1fr_.95fr] lg:items-center lg:py-24">
      <div><p className="inline-flex items-center gap-2 rounded-full border border-cyan-300/20 bg-cyan-300/10 px-3 py-1.5 text-xs font-black uppercase tracking-[0.16em] text-cyan-200"><Sparkles className="h-3.5 w-3.5" /> Formação Completa Plugando IA</p><h1 className="mt-6 text-balance text-4xl font-black leading-[1.02] tracking-[-0.055em] sm:text-5xl md:text-6xl">Cinco cursos para transformar ideias em <span className="bg-gradient-to-r from-cyan-300 via-blue-300 to-violet-300 bg-clip-text text-transparent">sistemas e produtos reais.</span></h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-300">Comece com Vibe Coding, aprofunde arquitetura e mensageria, construa aplicações com IA e tire um SaaS do papel — em uma única formação.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Cta label="Quero a formação completa" /><a href="#cursos" className="inline-flex items-center justify-center rounded-xl border border-white/15 bg-white/[0.04] px-6 py-4 text-sm font-bold hover:bg-white/[0.08]">Conhecer os 5 cursos</a></div><div className="mt-7 flex flex-wrap gap-x-6 gap-y-3 text-sm text-slate-400">{["Acesso vitalício", "Atualizações futuras", "7 dias de garantia"].map(item => <span key={item} className="flex items-center gap-2"><CheckCircle2 className="h-4 w-4 text-cyan-300" />{item}</span>)}</div></div>
      <div className="relative"><div className="absolute -inset-8 rounded-[2.5rem] bg-gradient-to-br from-cyan-400/15 to-violet-500/15 blur-3xl" /><div className="relative grid gap-2 rounded-3xl border border-white/15 bg-[#0b1020] p-4 shadow-[0_35px_100px_rgba(0,0,0,.55)] sm:grid-cols-2">{courses.map((course, index) => <div key={course.title} className={`rounded-2xl border border-white/10 bg-white/[0.04] p-4 ${index === 0 ? "sm:col-span-2" : ""}`}><span className="text-[10px] font-black uppercase tracking-widest text-cyan-300">Curso {course.number}</span><strong className="mt-2 block text-sm text-white">{course.title}</strong></div>)}</div><div className="relative mx-4 -mt-4 grid grid-cols-3 overflow-hidden rounded-2xl border border-white/10 bg-[#0b1020]/95 shadow-xl"><div className="p-4 text-center"><strong className="block text-xl font-black">5</strong><span className="text-xs text-slate-500">cursos</span></div><div className="border-x border-white/10 p-4 text-center"><strong className="block text-xl font-black text-cyan-300">62%</strong><span className="text-xs text-slate-500">de economia</span></div><div className="p-4 text-center"><strong className="block text-xl font-black">7 dias</strong><span className="text-xs text-slate-500">de garantia</span></div></div></div>
    </div></section>

    <section className="mx-auto max-w-7xl px-5 py-20 md:px-8 md:py-28"><Heading eyebrow="Uma formação, uma jornada" title="Não são cinco cursos soltos. É uma visão completa de produto e engenharia." description="Cada curso resolve uma parte da jornada: idealizar, pensar, conectar, potencializar com IA e publicar um produto real." /><div className="mt-14 grid gap-4 md:grid-cols-2 lg:grid-cols-4">{[
      { icon: Layers3, title: "Pense", text: "Organize responsabilidades e tome decisões de arquitetura." }, { icon: Workflow, title: "Conecte", text: "Crie comunicação assíncrona e fluxos mais resilientes." }, { icon: Bot, title: "Potencialize", text: "Adicione IA, contexto, dados e ações à aplicação." }, { icon: Rocket, title: "Publique", text: "Construa, monetize e coloque um SaaS no ar." },
    ].map(({ icon: Icon, title, text }, index) => <article key={title} className="relative rounded-2xl border border-white/10 bg-white/[0.035] p-6"><span className="grid h-11 w-11 place-items-center rounded-xl border border-cyan-300/20 bg-cyan-300/10 text-cyan-300"><Icon className="h-5 w-5" /></span><span className="absolute right-5 top-5 font-mono text-xs text-slate-700">0{index + 1}</span><h3 className="mt-6 text-xl font-black">{title}</h3><p className="mt-3 text-sm leading-7 text-slate-400">{text}</p></article>)}</div></section>

    <section id="cursos" className="scroll-mt-6 border-y border-white/[0.08] bg-[#090d19]"><div className="mx-auto max-w-7xl px-5 py-20 md:px-8 md:py-28"><Heading eyebrow="Tudo que você recebe" title="Cinco cursos completos para avançar da ideia à entrega." description="Siga a sequência sugerida ou comece pelo desafio mais importante para o seu momento profissional." /><div className="mt-14 grid gap-5 lg:grid-cols-2">{courses.map(course => { const Icon = course.icon; return <article key={course.title} className="group rounded-3xl border border-white/10 bg-[#0c111f] p-6 transition hover:-translate-y-1 hover:border-white/20 md:p-8"><div className="flex items-start justify-between"><span className={`grid h-12 w-12 place-items-center rounded-xl border ${course.color}`}><Icon className="h-6 w-6" /></span><span className="font-mono text-xs font-bold text-slate-600">CURSO {course.number}</span></div><h3 className="mt-6 text-2xl font-black md:text-3xl">{course.title}</h3><p className="mt-4 leading-7 text-slate-400">{course.promise}</p><ul className="mt-6 grid gap-3 sm:grid-cols-2">{course.topics.map(topic => <li key={topic} className="flex gap-2 text-sm text-slate-300"><Check className="mt-0.5 h-4 w-4 shrink-0 text-cyan-300" />{topic}</li>)}</ul><Link href={course.href} className="mt-7 inline-flex items-center gap-2 text-sm font-black text-cyan-300">Ver detalhes do curso <ArrowRight className="h-4 w-4" /></Link></article>; })}</div></div></section>

    <section className="mx-auto grid max-w-7xl gap-12 px-5 py-20 md:px-8 md:py-28 lg:grid-cols-[.9fr_1.1fr] lg:items-center"><div><p className="text-xs font-black uppercase tracking-[0.24em] text-cyan-300">Valor que continua crescendo</p><h2 className="mt-4 text-balance text-4xl font-black tracking-[-0.045em] md:text-5xl">Compre uma vez. Continue aprendendo sempre.</h2><p className="mt-5 text-lg leading-8 text-slate-400">Seu acesso não expira. Quando os cursos receberem melhorias, novas aulas ou atualizações, o conteúdo também ficará disponível para você sem uma nova compra.</p></div><div className="grid gap-4 sm:grid-cols-2">{[
      { icon: Infinity, title: "Acesso vitalício", text: "Estude no seu ritmo e retorne às aulas sempre que precisar." }, { icon: RefreshCw, title: "Futuras atualizações", text: "Receba as evoluções dos cinco cursos na sua matrícula." }, { icon: Code2, title: "Conhecimento aplicável", text: "Conceitos conectados a código, ferramentas e projetos reais." }, { icon: Zap, title: "Visão integrada", text: "Vibe Coding, arquitetura, backend, IA e produto na mesma jornada." },
    ].map(({ icon: Icon, title, text }) => <article key={title} className="rounded-2xl border border-white/10 bg-white/[0.035] p-6"><Icon className="h-6 w-6 text-cyan-300" /><h3 className="mt-5 text-lg font-black">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-400">{text}</p></article>)}</div></section>

    <section id="oferta" className="relative scroll-mt-6 border-y border-cyan-300/20 bg-cyan-300/[0.045]"><div className="relative mx-auto grid max-w-6xl gap-10 px-5 py-20 md:px-8 md:py-28 lg:grid-cols-[1.05fr_.95fr] lg:items-center"><div><p className="text-xs font-black uppercase tracking-[0.24em] text-cyan-300">Oferta da formação completa</p><h2 className="mt-4 text-balance text-4xl font-black tracking-[-0.045em] md:text-5xl">Leve os cinco cursos por uma única matrícula.</h2><p className="mt-5 max-w-xl text-lg leading-8 text-slate-300">Separadamente, os cursos custam {currency(REGULAR_PRICE)}. No combo, você recebe todos por {currency(PRICE)} e economiza {currency(SAVINGS)}.</p><div className="mt-8 grid gap-3 sm:grid-cols-2">{[...courses.map(c => c.title), "Acesso vitalício", "Futuras atualizações"].map(item => <div key={item} className="flex items-center gap-3 text-sm font-semibold text-slate-300"><CheckCircle2 className="h-4 w-4 shrink-0 text-cyan-300" />{item}</div>)}</div></div><aside className="rounded-3xl border border-cyan-300/30 bg-[#090d19] p-7 shadow-[0_30px_100px_rgba(0,0,0,.45)] md:p-8"><div className="flex flex-wrap items-center justify-between gap-3"><span className="rounded-full bg-cyan-300/10 px-3 py-1.5 text-xs font-black uppercase text-cyan-200">Combo completo</span><span className="text-sm font-bold text-emerald-300">Economize {currency(SAVINGS)}</span></div><div className="mt-7 border-b border-white/10 pb-6"><span className="text-sm text-slate-500">De <s>{currency(REGULAR_PRICE)}</s> por apenas</span><strong className="mt-2 block text-5xl font-black tracking-[-0.055em] md:text-6xl">{currency(PRICE)}</strong><span className="mt-2 block text-sm text-slate-400">pagamento único • acesso vitalício</span></div><Cta label="Quero garantir os 5 cursos" className="mt-6 w-full" />{!checkoutReady ? <p className="mt-3 rounded-lg border border-cyan-300/15 bg-cyan-300/5 p-2 text-center text-xs text-cyan-100/70">Checkout em configuração.</p> : null}<div className="mt-6 flex items-start gap-3"><ShieldCheck className="mt-0.5 h-5 w-5 shrink-0 text-emerald-300" /><p className="text-xs leading-5 text-slate-400"><strong className="text-slate-200">Você tem 7 dias de garantia.</strong> Conheça a formação e, se ela não for para você, solicite o cancelamento dentro desse prazo.</p></div></aside></div></section>

    <section className="mx-auto max-w-4xl px-5 py-20 md:px-8 md:py-24"><Heading eyebrow="Perguntas frequentes" title="Tudo claro antes de começar." description="As informações essenciais para você escolher a formação com segurança." /><div className="mt-10 space-y-3">{[
      ["Quais cursos estão incluídos?", "Vibe Coding para Leigos, Arquitetura de Software, RabbitMQ com .NET, Criando SaaS com Antigravity e Fundamentos de IA Generativa."], ["O acesso é realmente vitalício?", "Sim. Você poderá acessar os cursos no seu ritmo e voltar ao conteúdo sempre que precisar."], ["As futuras atualizações estão incluídas?", "Sim. Melhorias, modificações e novos conteúdos adicionados futuramente aos cursos ficarão disponíveis para você."], ["Posso estudar em qualquer ordem?", "Sim. Para quem está começando, a sugestão é iniciar por Vibe Coding para Leigos e Fundamentos de IA antes de avançar para os demais cursos."], ["Como funciona a garantia?", "Você tem 7 dias após a compra para conhecer a formação e solicitar o cancelamento caso ela não faça sentido para você."], ["Quanto economizo com o combo?", `Os cinco cursos separados custam ${currency(REGULAR_PRICE)}. O combo custa ${currency(PRICE)}, uma economia de ${currency(SAVINGS)}.`],
    ].map(([question, answer], index) => <TrackedAccordion key={question} title={question} pageKey={PAGE_KEY} pagePath={PAGE_PATH} pageTitle={PAGE_TITLE} eventName={`faq_${index + 1}_open`} className="!rounded-2xl !border-white/10 !bg-white/[0.025] !p-5" titleClassName="!font-bold !text-white" contentClassName="!text-slate-400" iconClassName="!border-white/10 !bg-white/[0.04] !text-cyan-300"><p>{answer}</p></TrackedAccordion>)}</div></section>

    <section className="border-t border-white/[0.08] bg-[#090d19]"><div className="mx-auto max-w-5xl px-5 py-20 text-center md:px-8 md:py-24"><h2 className="text-balance text-4xl font-black tracking-[-0.045em] md:text-5xl">Cinco cursos, uma única matrícula e acesso para sempre.</h2><p className="mt-5 text-lg text-slate-400">Sua próxima fase pode começar com uma visão mais completa.</p><Cta label="Quero entrar na Formação Completa" className="mt-8 sm:min-w-80" /></div></section>
    <footer className="border-t border-white/[0.08]"><div className="mx-auto flex max-w-7xl flex-col gap-4 px-5 py-8 text-sm text-slate-500 md:flex-row md:items-center md:justify-between md:px-8"><strong className="text-white">Plugando IA</strong><div className="flex gap-5"><Link href="/terms">Termos</Link><Link href="/privacy">Privacidade</Link><Link href="/cursos">Todos os cursos</Link></div></div></footer>
    {checkoutReady ? <MobileStickyCTA title="Formação Completa" priceLabel={currency(PRICE)} href={checkoutUrl} label="Quero os 5 cursos" pageKey={PAGE_KEY} pagePath={PAGE_PATH} pageTitle={PAGE_TITLE} value={PRICE} currency="BRL" className="!border-cyan-300/20 !bg-[#060913]/95" priceClassName="!text-cyan-300" buttonClassName="!rounded-lg !bg-none !bg-cyan-300 !text-slate-950" hideGlow /> : null}
  </main>;
}
