import Link from "next/link";
import {
  ArrowDown, ArrowRight, Blocks, Bot, BrainCircuit, BriefcaseBusiness, Check, CheckCircle2,
  CircleDollarSign, CloudUpload, Code2, Database, FileCode2, GitBranch, Globe2, Laptop,
  LayoutDashboard, Lightbulb, ListChecks, MessageSquareText, MousePointer2, Rocket,
  ShieldCheck, Sparkles, Terminal, WandSparkles, Workflow,
} from "lucide-react";
import { MetaPixelScript } from "@/components/MetaPixelScript";
import { SalesPageTracker, SalesViewContentTracker } from "@/components/SalesPageTracker";
import { MobileStickyCTA, SectionViewTracker, TrackedAccordion, TrackedCheckoutButton } from "@/components/course-completo/interactive";

type Props = { checkoutUrl: string; metaPixelId?: string };
const PAGE_KEY = "vibecode";
const PAGE_PATH = "/vibecode";
const PAGE_TITLE = "Vibe Coding para Leigos | Crie Aplicações com IA";
const PRICE = 79.9;
const eventData = { content_name: "Vibe Coding para Leigos", content_category: "Curso", content_type: "product", value: PRICE, currency: "BRL" };

const painPoints = [
  "Tenho uma ideia de sistema, mas não sei como começar.", "Não sei programar e a parte técnica parece distante.",
  "Já pedi algo para uma IA, mas o projeto virou uma bagunça.", "Não sei o que são frontend, backend ou banco de dados.",
  "Quero criar uma solução para o meu próprio negócio.", "Vejo pessoas criando aplicativos com IA e quero aprender como fazer.",
];
const possibilities = [[Globe2,"Sites para pequenos negócios"],[LayoutDashboard,"Sistemas administrativos"],[MousePointer2,"Páginas de vendas"],[ListChecks,"Agendamentos e catálogos"],[Blocks,"MVPs e pequenos SaaS"],[BriefcaseBusiness,"Protótipos para clientes"]] as const;
const learningGroups = [
  { title: "Pensar com IA", icon: BrainCircuit, items: ["Fundamentos de Vibe Coding", "Requisitos e decisões", "ChatGPT no planejamento", "SPEC e divisão em tarefas"] },
  { title: "Construir", icon: Code2, items: ["Codex e VS Code", "Arquivos, pastas e terminal", "Node.js, frontend e backend", "APIs e banco de dados"] },
  { title: "Evoluir com segurança", icon: ShieldCheck, items: ["Autenticação e arquivos", "Git e GitHub", "Debug, testes e validação", "Deploy e publicação"] },
  { title: "Ampliar possibilidades", icon: WandSparkles, items: ["Skills e Tools", "Introdução a MCP", "Projetos para negócios", "Método para novas ideias"] },
] as const;
const method = ["Tenha uma ideia", "Converse com a IA", "Defina o que será construído", "Crie a SPEC", "Crie o plano", "Divida em pequenas tarefas", "Implemente com IA", "Teste", "Corrija", "Valide", "Crie um checkpoint com Git", "Publique"];
const faq = [
  ["Preciso saber programar?", "Não. O curso foi pensado para quem está começando e apresenta cada conceito quando ele se torna necessário para avançar no projeto."],
  ["Preciso ter experiência com Inteligência Artificial?", "Não. Você aprenderá como conversar com as ferramentas, fornecer contexto e avaliar o que elas produzem."],
  ["Vou precisar escrever código?", "Você terá contato com código, mas não precisa chegar sabendo escrever. A IA ajuda a produzir o código e você aprende a orientar, analisar, testar e corrigir o resultado."],
  ["Qual projeto será desenvolvido?", "Uma plataforma de imobiliária completa, com páginas públicas, filtros, banco de dados, autenticação, área administrativa e publicação na internet."],
  ["O curso ensina somente a criar uma imobiliária?", "Não. A imobiliária é o projeto didático. O foco é aprender um processo que você poderá adaptar às suas próprias ideias."],
  ["Quais ferramentas serão utilizadas?", "ChatGPT para pensar e organizar, Codex para construir, VS Code, terminal, Node.js, Git, GitHub e as ferramentas necessárias para publicar a aplicação."],
  ["Consigo aplicar o método em outros projetos?", "Sim. Planejamento, SPEC, tarefas pequenas, testes e validação formam um processo reutilizável em diferentes tipos de aplicação."],
  ["Vibe Coding pode ser usado para criar projetos para clientes?", "Pode. O método ajuda a transformar problemas reais em soluções digitais. Isso abre possibilidades de prestação de serviços, sem promessa de renda ou resultado financeiro."],
  ["Preciso pagar pelas ferramentas utilizadas?", "Algumas ferramentas podem oferecer planos gratuitos e pagos. Custos e limites podem mudar; você poderá escolher as opções adequadas ao seu projeto."],
  ["Vou aprender frontend e backend?", "Sim, de forma prática e progressiva. Você entenderá o papel de cada parte enquanto constrói a aplicação do curso."],
] as const;

function money(value: number) { return value.toLocaleString("pt-BR", { style: "currency", currency: "BRL" }); }
function SectionHeading({ eyebrow, title, text, light = false }: { eyebrow: string; title: string; text?: string; light?: boolean }) {
  return <div className="max-w-3xl"><p className={`text-xs font-black uppercase tracking-[0.22em] ${light ? "text-lime-300" : "text-violet-700"}`}>{eyebrow}</p><h2 className={`mt-4 text-balance text-3xl font-black leading-[1.08] tracking-[-0.045em] sm:text-4xl md:text-5xl ${light ? "text-white" : "text-[#171329]"}`}>{title}</h2>{text ? <p className={`mt-5 max-w-2xl text-lg leading-8 ${light ? "text-slate-300" : "text-slate-600"}`}>{text}</p> : null}</div>;
}

export function VibeCodeLanding({ checkoutUrl, metaPixelId }: Props) {
  const checkoutReady = /^https?:\/\//.test(checkoutUrl);
  function Cta({ label, className = "" }: { label: string; className?: string }) {
    if (!checkoutReady) return <a href="#oferta" className={`inline-flex items-center justify-center rounded-xl bg-[#b8f34a] px-6 py-4 text-center text-sm font-black uppercase tracking-wide text-[#171329] transition hover:-translate-y-0.5 hover:bg-lime-300 ${className}`}>{label}<ArrowRight className="ml-2 h-4 w-4" /></a>;
    return <TrackedCheckoutButton href={checkoutUrl} label={label} pageKey={PAGE_KEY} pagePath={PAGE_PATH} pageTitle={PAGE_TITLE} value={PRICE} currency="BRL" customEvent="vibecode_checkout_click" eventData={eventData} hideGlow className={`!rounded-xl !bg-none !bg-[#b8f34a] !px-6 !py-4 !font-black !uppercase !tracking-wide !text-[#171329] hover:!-translate-y-0.5 hover:!bg-lime-300 ${className}`} />;
  }

  return <main className="min-h-screen overflow-hidden bg-[#fbfaf7] text-[#171329] selection:bg-violet-200">
    <MetaPixelScript pixelId={metaPixelId} />
    <SalesPageTracker pageKey={PAGE_KEY} pagePath={PAGE_PATH} pageTitle={PAGE_TITLE} metadata={{ offerPrice: PRICE, currency: "BRL", offerName: "Vibe Coding para Leigos" }} />
    <SalesViewContentTracker pageKey={PAGE_KEY} pagePath={PAGE_PATH} pageTitle={PAGE_TITLE} currency="BRL" value={PRICE} metadata={{ contentName: "Vibe Coding para Leigos", contentType: "course" }} />
    <SectionViewTracker selectorId="metodo" pageKey={PAGE_KEY} pagePath={PAGE_PATH} pageTitle={PAGE_TITLE} eventName="method_view" /><SectionViewTracker selectorId="oferta" pageKey={PAGE_KEY} pagePath={PAGE_PATH} pageTitle={PAGE_TITLE} eventName="offer_view" />

    <div className="border-b border-violet-200 bg-violet-100 px-4 py-2.5 text-center text-xs font-bold text-violet-950 sm:text-sm">Novo curso • da ideia à aplicação com Inteligência Artificial</div>
    <header className="border-b border-slate-200/80 bg-[#fbfaf7]/90 backdrop-blur"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4 md:px-8"><Link href="/cursos" className="flex items-center gap-2 text-lg font-black tracking-[-0.03em]"><span className="grid h-9 w-9 place-items-center rounded-xl bg-violet-700 text-white"><Sparkles className="h-4 w-4" /></span>Plugando IA</Link><a href="#oferta" className="rounded-lg border border-violet-200 px-4 py-2 text-sm font-bold text-violet-800 hover:bg-violet-50">Ver o curso</a></div></header>

    <section className="relative border-b border-slate-200/80"><div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_78%_20%,rgba(124,58,237,.14),transparent_28%),radial-gradient(circle_at_10%_80%,rgba(184,243,74,.22),transparent_25%)]" /><div className="relative mx-auto grid max-w-7xl gap-12 px-5 py-14 md:px-8 md:py-20 lg:grid-cols-[1.05fr_.95fr] lg:items-center lg:py-24">
      <div><p className="inline-flex items-center gap-2 rounded-full border border-violet-200 bg-white px-3 py-1.5 text-xs font-black uppercase tracking-[0.15em] text-violet-700 shadow-sm"><WandSparkles className="h-3.5 w-3.5" /> Vibe Coding para Leigos</p><h1 className="mt-6 text-balance text-4xl font-black leading-[1.02] tracking-[-0.055em] sm:text-5xl md:text-6xl lg:text-7xl">Você não precisa saber programar para <span className="text-violet-700">tirar sua ideia do papel.</span></h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-600">Aprenda a usar Inteligência Artificial para planejar, construir, testar e publicar aplicações reais — mesmo começando do zero.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row sm:items-center"><Cta label="Quero criar meu primeiro projeto" /><a href="#como-funciona" className="inline-flex items-center justify-center px-5 py-4 text-sm font-bold text-slate-700">Entender como funciona <ArrowDown className="ml-2 h-4 w-4" /></a></div><div className="mt-7 flex flex-wrap gap-x-6 gap-y-3 text-sm text-slate-600">{["Curso completo", "Acesso online", "Projeto prático", money(PRICE)].map(item => <span key={item} className="flex items-center gap-2"><CheckCircle2 className="h-4 w-4 text-violet-700" />{item}</span>)}</div><p className="mt-4 text-sm font-semibold text-violet-800">Comece mesmo sem experiência com programação.</p></div>
      <div className="relative"><div className="absolute -inset-8 rounded-full bg-violet-300/25 blur-3xl" /><div className="relative rounded-[2rem] border border-slate-200 bg-white p-4 shadow-[0_30px_90px_rgba(46,24,86,.18)] sm:p-6"><div className="flex items-center gap-2 border-b border-slate-100 pb-4"><span className="h-2.5 w-2.5 rounded-full bg-rose-400" /><span className="h-2.5 w-2.5 rounded-full bg-amber-400" /><span className="h-2.5 w-2.5 rounded-full bg-emerald-400" /><span className="ml-2 text-xs font-bold text-slate-400">meu-primeiro-projeto</span></div><div className="mt-5 grid gap-3 sm:grid-cols-[.7fr_1.3fr]"><div className="rounded-2xl bg-[#171329] p-4 text-white"><Lightbulb className="h-6 w-6 text-lime-300" /><p className="mt-8 text-xs uppercase tracking-widest text-slate-400">Sua ideia</p><strong className="mt-2 block text-lg">Um sistema que resolve um problema real</strong></div><div className="space-y-3">{[[MessageSquareText,"ChatGPT","organiza a ideia e cria a SPEC"],[Code2,"Codex","planeja e constrói com você"],[Rocket,"Aplicação","testada e publicada na internet"]].map(([Icon,title,text], index) => { const CardIcon = Icon as typeof Code2; return <div key={String(title)} className="flex items-center gap-3 rounded-2xl border border-slate-200 p-3"><span className={`grid h-10 w-10 shrink-0 place-items-center rounded-xl ${index === 2 ? "bg-lime-100 text-lime-800" : "bg-violet-100 text-violet-700"}`}><CardIcon className="h-5 w-5" /></span><div><strong className="text-sm">{String(title)}</strong><p className="text-xs leading-5 text-slate-500">{String(text)}</p></div></div>; })}</div></div><div className="mt-4 flex items-center justify-center gap-2 rounded-xl bg-violet-50 px-3 py-3 text-xs font-black uppercase tracking-[0.12em] text-violet-800"><span>Ideia</span><ArrowRight className="h-3.5 w-3.5" /><span>IA</span><ArrowRight className="h-3.5 w-3.5" /><span>Aplicação</span></div></div></div>
    </div></section>

    <section className="mx-auto max-w-7xl px-5 py-20 md:px-8 md:py-28"><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr] lg:items-start"><SectionHeading eyebrow="Isso parece familiar?" title="Você tem uma ideia, mas trava quando chega na parte técnica?" text="A distância entre imaginar e construir parece enorme quando ninguém mostra o próximo passo com clareza." /><div className="grid gap-3 sm:grid-cols-2">{painPoints.map((item,index) => <article key={item} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><span className="text-xs font-black text-violet-400">0{index + 1}</span><p className="mt-3 font-bold leading-6 text-slate-800">“{item}”</p></article>)}</div></div><div className="mt-10 rounded-2xl bg-violet-700 px-6 py-5 text-center text-lg font-black text-white">Foi para essas pessoas que o Vibe Coding para Leigos foi criado.</div></section>

    <section id="como-funciona" className="scroll-mt-8 bg-[#171329] text-white"><div className="mx-auto max-w-7xl px-5 py-20 md:px-8 md:py-28"><SectionHeading light eyebrow="Sem definição complicada" title="Vibe Coding é construir software trabalhando em conjunto com a IA." text="Você descreve o que precisa, fornece contexto, toma decisões, acompanha o trabalho da IA, testa o resultado e evolui o projeto." /><div className="mt-12 grid gap-4 lg:grid-cols-3">{[[Lightbulb,"Você","Ideia, contexto e decisões"],[BrainCircuit,"Inteligência Artificial","Planejamento e desenvolvimento"],[Laptop,"Projeto funcionando","Resultado testado e validado"]].map(([Icon,title,text],index) => { const StepIcon = Icon as typeof Laptop; return <article key={String(title)} className="relative rounded-3xl border border-white/10 bg-white/[.05] p-7"><StepIcon className="h-8 w-8 text-lime-300" /><p className="mt-10 text-xs font-black uppercase tracking-widest text-violet-300">Etapa 0{index + 1}</p><h3 className="mt-2 text-2xl font-black">{String(title)}</h3><p className="mt-3 text-slate-400">{String(text)}</p>{index < 2 ? <ArrowRight className="absolute -right-7 top-1/2 z-10 hidden h-6 w-6 text-violet-300 lg:block" /> : null}</article>; })}</div><div className="mt-8 grid gap-4 rounded-2xl border border-lime-300/20 bg-lime-300/[.06] p-6 sm:grid-cols-2"><p><strong className="text-lime-300">A IA ajuda</strong><br /><span className="text-slate-300">a escrever e alterar o código.</span></p><p><strong className="text-lime-300">Você aprende</strong><br /><span className="text-slate-300">a orientar, analisar e validar a IA.</span></p></div></div></section>

    <section className="mx-auto max-w-7xl px-5 py-20 md:px-8 md:py-28"><SectionHeading eyebrow="Novas possibilidades" title="Uma nova habilidade que pode abrir novos caminhos." text="A IA reduziu a barreira técnica. Isso pode ajudar pessoas que nunca programaram a transformar problemas reais em soluções digitais — para si mesmas, seus negócios ou clientes." /><div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{possibilities.map(([Icon,title]) => <article key={title} className="flex items-center gap-4 rounded-2xl border border-slate-200 bg-white p-5"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-violet-100 text-violet-700"><Icon className="h-5 w-5" /></span><h3 className="font-black">{title}</h3></article>)}</div><div className="mt-10 rounded-3xl bg-lime-200 p-7 md:flex md:items-center md:justify-between md:gap-8"><CircleDollarSign className="h-10 w-10 text-lime-900" /><p className="mt-4 text-2xl font-black tracking-tight text-lime-950 md:mt-0 md:text-3xl">Talvez sua primeira aplicação seja para você.<br />A segunda pode ser para um cliente.</p><p className="mt-4 max-w-sm text-sm leading-6 text-lime-900 md:mt-0">Uma possibilidade — sem promessas de renda ou resultado garantido.</p></div></section>

    <section className="border-y border-slate-200 bg-white"><div className="mx-auto grid max-w-7xl gap-12 px-5 py-20 md:px-8 md:py-28 lg:grid-cols-2 lg:items-center"><div><SectionHeading eyebrow="Aprenda no momento certo" title="Você ainda não precisa entender tudo." text="Terminal, frontend, backend, API, banco de dados, Git e deploy deixam de ser uma lista assustadora quando cada conceito aparece para resolver o próximo problema." /><div className="mt-8 flex flex-wrap gap-2">{["Terminal","Frontend","Backend","API","Banco de dados","Git","Deploy"].map(item => <span key={item} className="rounded-full border border-slate-200 bg-slate-50 px-4 py-2 text-sm font-bold text-slate-600">{item}</span>)}</div></div><div className="rounded-3xl bg-violet-700 p-6 text-white shadow-xl md:p-8"><p className="text-xs font-black uppercase tracking-widest text-violet-200">A filosofia do curso</p><div className="mt-8 space-y-3">{["Conceito","Exemplo","Demonstração","Prática"].map((item,index) => <div key={item} className="flex items-center gap-4 rounded-2xl bg-white/[.09] p-4"><span className="grid h-9 w-9 place-items-center rounded-full bg-lime-300 font-black text-violet-950">{index + 1}</span><strong className="text-lg">{item}</strong>{index < 3 ? <ArrowDown className="ml-auto h-4 w-4 text-violet-200" /> : <CheckCircle2 className="ml-auto h-5 w-5 text-lime-300" />}</div>)}</div><p className="mt-6 leading-7 text-violet-100">Você aprende cada conceito somente quando ele é necessário para dar o próximo passo.</p></div></div></section>

    <section className="mx-auto max-w-7xl px-5 py-20 md:px-8 md:py-28"><SectionHeading eyebrow="Projeto do início ao fim" title="Nada de ficar apenas na teoria." text="Durante o curso, você acompanhará a construção de uma plataforma de imobiliária real. Ela é o laboratório prático para aprender o processo completo." /><div className="mt-12 grid gap-8 lg:grid-cols-[.9fr_1.1fr]"><div className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-lg"><div className="flex items-center gap-2 bg-[#171329] px-5 py-4"><span className="h-2.5 w-2.5 rounded-full bg-rose-400" /><span className="h-2.5 w-2.5 rounded-full bg-amber-400" /><span className="h-2.5 w-2.5 rounded-full bg-emerald-400" /><span className="ml-2 text-xs text-slate-400">projeto-imobiliaria.app</span></div><div className="p-5"><div className="h-36 rounded-2xl bg-gradient-to-br from-violet-200 via-white to-lime-100 p-5"><span className="rounded-full bg-white px-3 py-1 text-xs font-bold text-violet-700">Imóveis em destaque</span><div className="mt-10 grid grid-cols-3 gap-2"><span className="h-8 rounded-lg bg-white/80" /><span className="h-8 rounded-lg bg-white/80" /><span className="h-8 rounded-lg bg-violet-700" /></div></div><div className="mt-4 grid grid-cols-3 gap-3">{[1,2,3].map(item => <div key={item} className="rounded-xl border border-slate-100 p-2"><div className="h-12 rounded-lg bg-slate-100" /><div className="mt-2 h-2 w-3/4 rounded bg-slate-200" /><div className="mt-2 h-2 w-1/2 rounded bg-slate-100" /></div>)}</div></div></div><div className="grid gap-3 sm:grid-cols-2">{["Página inicial e listagem","Venda, aluguel e filtros","Detalhes e múltiplas imagens","Banco de dados","Autenticação","Área administrativa","Cadastro, edição e exclusão","Armazenamento de imagens","Segurança básica","Publicação na internet"].map(item => <div key={item} className="flex items-center gap-3 rounded-xl border border-slate-200 bg-white p-4 text-sm font-bold"><Check className="h-4 w-4 shrink-0 text-violet-700" />{item}</div>)}</div></div><div className="mt-8 rounded-2xl border-2 border-violet-200 bg-violet-50 p-6 text-center text-xl font-black text-violet-950">Você não está aprendendo a copiar uma imobiliária.<br /><span className="text-violet-700">Está aprendendo um processo para construir suas próprias ideias.</span></div></section>

    <section className="bg-[#171329] text-white"><div className="mx-auto max-w-7xl px-5 py-20 md:px-8 md:py-28"><SectionHeading light eyebrow="Duas ferramentas, papéis claros" title="ChatGPT para pensar. Codex para construir." text="As ferramentas podem fazer mais, mas essa divisão simples ajuda você a visualizar e conduzir o processo." /><div className="mt-12 grid gap-5 md:grid-cols-2">{[[MessageSquareText,"ChatGPT → pensar",["Descobrir requisitos","Organizar a ideia","Tomar decisões","Criar a especificação"]],[Code2,"Codex → construir",["Analisar o projeto","Planejar a implementação","Criar e alterar arquivos","Testar e corrigir"]]].map(([Icon,title,items]) => { const ToolIcon = Icon as typeof Code2; return <article key={String(title)} className="rounded-3xl border border-violet-400/20 bg-white/[.05] p-7 md:p-9"><ToolIcon className="h-9 w-9 text-lime-300" /><p className="mt-8 text-xs font-black uppercase tracking-widest text-violet-300">{String(title)}</p><ul className="mt-5 space-y-3">{(items as string[]).map(item => <li key={item} className="flex gap-3 text-slate-300"><Check className="mt-1 h-4 w-4 text-lime-300" />{item}</li>)}</ul></article>; })}</div></div></section>

    <section className="mx-auto max-w-7xl px-5 py-20 md:px-8 md:py-28"><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><SectionHeading eyebrow="SPEC-driven development" title="Antes de pedir código, explique o que precisa ser construído." text="A SPEC é um documento simples: registra funcionalidades, regras, limites e decisões do projeto. Assim, a IA recebe contexto e o desenvolvimento deixa de ser aleatório." /><div className="rounded-3xl border border-slate-200 bg-white p-5 shadow-lg md:p-7"><div className="flex items-center gap-3 border-b border-slate-100 pb-5"><FileCode2 className="h-6 w-6 text-violet-700" /><div><strong className="block">SPEC: minha aplicação</strong><span className="text-xs text-slate-400">fonte de verdade do projeto</span></div></div><div className="mt-5 flex flex-wrap gap-2">{["Ideia","Conversa com IA","Decisões","SPEC","Plano","Tarefas","Desenvolvimento"].map((item,index) => <span key={item} className={`rounded-lg px-3 py-2 text-xs font-black ${index === 3 ? "bg-violet-700 text-white" : "bg-slate-100 text-slate-600"}`}>{item}</span>)}</div><div className="mt-6 space-y-3">{["O que vamos construir","Quais regras precisam ser respeitadas","O que já foi decidido","Como saberemos que está funcionando"].map(item => <p key={item} className="flex items-center gap-3 rounded-xl border border-slate-100 p-3 text-sm font-semibold"><CheckCircle2 className="h-4 w-4 text-violet-700" />{item}</p>)}</div></div></div></section>

    <section className="border-y border-slate-200 bg-white"><div className="mx-auto max-w-7xl px-5 py-20 md:px-8 md:py-28"><SectionHeading eyebrow="Conteúdo sem susto" title="O que você vai aprender." text="Os temas técnicos aparecem organizados por objetivo. Você não precisa dominar tudo de uma vez." /><div className="mt-12 grid gap-5 md:grid-cols-2 lg:grid-cols-4">{learningGroups.map(({ title,icon: Icon,items }) => <article key={title} className="rounded-3xl border border-slate-200 p-6"><span className="grid h-12 w-12 place-items-center rounded-xl bg-violet-100 text-violet-700"><Icon className="h-6 w-6" /></span><h3 className="mt-6 text-xl font-black">{title}</h3><ul className="mt-5 space-y-3">{items.map(item => <li key={item} className="flex gap-2 text-sm leading-6 text-slate-600"><Check className="mt-1 h-4 w-4 shrink-0 text-violet-600" />{item}</li>)}</ul></article>)}</div></div></section>

    <section id="metodo" className="scroll-mt-8 bg-violet-700 text-white"><div className="mx-auto max-w-7xl px-5 py-20 md:px-8 md:py-28"><SectionHeading light eyebrow="Existe um processo" title="Da ideia à publicação, um passo de cada vez." text="Vibe Coding não é pedir “IA, crie meu aplicativo”. É planejar, pedir, analisar, testar, corrigir e validar." /><ol className="mt-12 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{method.map((item,index) => <li key={item} className="flex items-center gap-4 rounded-2xl border border-white/15 bg-white/[.08] p-4"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-lime-300 text-sm font-black text-violet-950">{String(index + 1).padStart(2,"0")}</span><strong className="text-sm">{item}</strong></li>)}</ol></div></section>

    <section className="mx-auto grid max-w-7xl gap-12 px-5 py-20 md:px-8 md:py-28 lg:grid-cols-2 lg:items-center"><div><SectionHeading eyebrow="Responsabilidade desde o começo" title="A IA acelera. Você continua no controle." text="O curso não ensina a aceitar qualquer resultado. Você aprende a trabalhar com segurança, contexto e checkpoints." /><div className="mt-8 grid gap-3 sm:grid-cols-2">{["Pequenas etapas","Testes frequentes","Análise das alterações","Explicações antes de avançar","Proteção de senhas e API Keys","Variáveis de ambiente","Checkpoints com Git","Validação antes de continuar"].map(item => <p key={item} className="flex gap-3 text-sm font-semibold text-slate-700"><ShieldCheck className="h-5 w-5 shrink-0 text-violet-700" />{item}</p>)}</div></div><div className="rounded-3xl bg-[#171329] p-7 text-white md:p-9"><div className="flex items-center justify-between"><Terminal className="h-7 w-7 text-lime-300" /><span className="text-xs font-mono text-slate-500">checkpoint seguro</span></div><div className="mt-8 space-y-4 font-mono text-sm"><p className="text-slate-500">$ antes de continuar...</p><p><span className="text-violet-300">01.</span> revisar alterações</p><p><span className="text-violet-300">02.</span> testar o fluxo</p><p><span className="text-violet-300">03.</span> corrigir com contexto</p><p><span className="text-violet-300">04.</span> salvar no Git</p><p className="rounded-lg bg-lime-300/10 p-3 text-lime-300">✓ etapa validada</p></div></div></section>

    <section className="border-y border-slate-200 bg-white"><div className="mx-auto max-w-7xl px-5 py-20 md:px-8 md:py-28"><SectionHeading eyebrow="Para quem é" title="Para quem tem vontade de construir — não um diploma de programação." text="Não é necessário conhecimento prévio. Curiosidade, uma ideia e disposição para seguir o processo são um ótimo começo." /><div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{["Tenho uma ideia de aplicativo","Tenho um pequeno negócio","Quero criar soluções para outras pessoas","Quero aprender Vibe Coding","Quero explorar uma possibilidade de renda extra","Quero entrar no desenvolvimento com IA","Não sei programar, mas quero começar","Quero tirar um projeto do papel"].map((item,index) => <article key={item} className="rounded-2xl border border-slate-200 p-5"><span className="text-xs font-black text-violet-400">0{index + 1}</span><p className="mt-3 font-black leading-6">{item}</p></article>)}</div></div></section>

    <section className="mx-auto max-w-7xl px-5 py-20 md:px-8 md:py-28"><SectionHeading eyebrow="A transformação" title="Você começa com uma ideia. Termina entendendo como transformá-la em produto." text="O objetivo não é prometer uma carreira instantânea. É dar a você experiência prática e um processo que possa ser repetido." /><div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{[[Laptop,"Aplicação funcional"],[Workflow,"Projeto organizado"],[Bot,"Experiência construindo com IA"],[Database,"Visão das partes da aplicação"],[GitBranch,"Processo reutilizável"],[CloudUpload,"Aplicação publicada"]].map(([Icon,title]) => { const ResultIcon = Icon as typeof Laptop; return <article key={String(title)} className="flex items-center gap-4 rounded-2xl bg-violet-50 p-5"><ResultIcon className="h-6 w-6 text-violet-700" /><strong>{String(title)}</strong></article>; })}</div></section>

    <section id="oferta" className="relative scroll-mt-8 bg-[#171329] text-white"><div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_70%_30%,rgba(124,58,237,.35),transparent_35%)]" /><div className="relative mx-auto grid max-w-6xl gap-10 px-5 py-20 md:px-8 md:py-28 lg:grid-cols-[1fr_.8fr] lg:items-center"><div><p className="text-xs font-black uppercase tracking-[.22em] text-lime-300">Vibe Coding para Leigos</p><h2 className="mt-4 text-balance text-4xl font-black tracking-[-.045em] md:text-5xl">Sua ideia pode ganhar uma primeira versão real.</h2><p className="mt-5 max-w-xl text-lg leading-8 text-slate-300">Curso completo, projeto prático e um processo para planejar, construir, testar e publicar com IA.</p><div className="mt-8 grid gap-3 sm:grid-cols-2">{["Comece do zero","Projeto de ponta a ponta","ChatGPT + Codex","Método reutilizável"].map(item => <p key={item} className="flex gap-2 text-sm font-semibold text-slate-300"><CheckCircle2 className="h-4 w-4 text-lime-300" />{item}</p>)}</div></div><aside className="rounded-3xl border border-white/15 bg-white/[.07] p-7 shadow-2xl backdrop-blur md:p-8"><span className="text-sm text-slate-400">Curso completo</span><strong className="mt-2 block text-5xl font-black tracking-[-.055em]">{money(PRICE)}</strong><span className="mt-2 block text-sm text-slate-400">pagamento único</span><Cta label="Quero começar agora" className="mt-7 w-full" />{checkoutReady ? <p className="mt-4 text-center text-xs leading-5 text-slate-400">Você poderá revisar as condições no checkout antes de concluir.</p> : <p className="mt-4 rounded-xl border border-amber-300/20 bg-amber-300/[.08] p-3 text-center text-xs leading-5 text-amber-100">Checkout em configuração. Defina <code className="font-mono">NEXT_PUBLIC_VIBECODE_CHECKOUT_URL</code> para ativar as matrículas.</p>}<p className="mt-5 text-center text-sm font-bold text-lime-300">Comece mesmo sem saber programar.</p></aside></div></section>

    <section className="mx-auto max-w-4xl px-5 py-20 md:px-8 md:py-24"><SectionHeading eyebrow="Perguntas frequentes" title="Respostas diretas antes de começar." text="Sem letras miúdas e sem promessas que o curso não pode cumprir." /><div className="mt-10 space-y-3">{faq.map(([question,answer],index) => <TrackedAccordion key={question} title={question} pageKey={PAGE_KEY} pagePath={PAGE_PATH} pageTitle={PAGE_TITLE} eventName={`faq_${index + 1}_open`} variant="light"><p>{answer}</p></TrackedAccordion>)}</div></section>
    <section className="border-t border-slate-200 bg-violet-50"><div className="mx-auto max-w-5xl px-5 py-20 text-center md:px-8 md:py-24"><Rocket className="mx-auto h-10 w-10 text-violet-700" /><h2 className="mt-6 text-balance text-4xl font-black tracking-[-.045em] md:text-5xl">Sua ideia não precisa continuar sendo apenas uma ideia.</h2><p className="mx-auto mt-5 max-w-3xl text-lg leading-8 text-slate-600">Você não precisa esperar aprender programação por anos para começar a construir. Aprenda a trabalhar com Inteligência Artificial e dê o primeiro passo para transformar suas ideias em aplicações.</p><strong className="mt-8 block text-3xl font-black text-violet-800">{money(PRICE)}</strong><Cta label="Quero tirar minha ideia do papel" className="mt-6 sm:min-w-96" /></div></section>
    <footer className="border-t border-slate-200 bg-white"><div className="mx-auto flex max-w-7xl flex-col gap-4 px-5 py-8 text-sm text-slate-500 md:flex-row md:items-center md:justify-between md:px-8"><strong className="text-[#171329]">Plugando IA</strong><div className="flex gap-5"><Link href="/terms">Termos</Link><Link href="/privacy">Privacidade</Link><Link href="/cursos">Todos os cursos</Link></div></div></footer>
    {checkoutReady ? <MobileStickyCTA title="Vibe Coding para Leigos" priceLabel={money(PRICE)} href={checkoutUrl} label="Quero começar" pageKey={PAGE_KEY} pagePath={PAGE_PATH} pageTitle={PAGE_TITLE} value={PRICE} currency="BRL" className="!border-violet-200 !bg-[#fbfaf7]/95" titleClassName="!text-[#171329]" priceClassName="!text-violet-700" buttonClassName="!rounded-lg !bg-none !bg-[#b8f34a] !text-[#171329]" hideGlow /> : null}
  </main>;
}
